# Generated by Django 5.0.6 on 2024-05-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskId', models.IntegerField()),
                ('TaskTitle', models.CharField(max_length=55)),
                ('TeacherN', models.CharField(max_length=55)),
                ('Description', models.TextField(max_length=160)),
                ('createdBy', models.CharField(max_length=15)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
