# Generated by Django 5.0.6 on 2024-05-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': []},
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('High', 'High'), ('Medium', 'Medium')], default='Low', max_length=6),
        ),
        migrations.AlterField(
            model_name='task',
            name='Description',
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
    ]
