# Generated by Django 5.0.6 on 2024-05-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_task_priority_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='TaskId',
            new_name='TaskId',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='createdBy',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='priority',
            new_name='choose',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='TaskTitle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='TeacherN',
            new_name='teacher',
        ),
    ]
