# Generated by Django 5.0.6 on 2024-05-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_taskid_task_id_rename_createdby_task_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='TaskId',
            new_name='Taskid',
        ),
    ]
