# Generated by Django 5.0.6 on 2024-05-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_taskid_task_taskid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='TaskId',
        ),
    ]
