# Generated by Django 5.0.6 on 2024-05-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_task_taskid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='TaskId',
            field=models.IntegerField(null=True),
        ),
    ]
