# Generated by Django 5.0.6 on 2024-05-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_taskid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='TaskId',
            new_name='Taskiid',
        ),
    ]
