# Generated by Django 5.0.6 on 2024-05-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='admin',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
