# Generated by Django 5.0.6 on 2024-05-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_task_taskiid_alter_task_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='choose',
            field=models.CharField(choices=[('Low', 'Low'), ('High', 'High'), ('Medium', 'Medium')], default='Low', max_length=6, null=True),
        ),
    ]
