# Generated by Django 5.0.6 on 2024-05-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='choose',
            field=models.CharField(choices=[('Low', 'Low'), ('High', 'High'), ('Medium', 'Medium')], max_length=6, null=True),
        ),
    ]
