# Generated by Django 5.0.6 on 2024-05-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availableTasks', '0002_task_createdby'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
